project:
  type: website
  output-dir: docs
  
website:
  navbar:
    title: "Avid Afzal"
    left:
      - href: index.qmd
        text: Home
      - href: blogs.qmd
        text: Blogs

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full
    main-container: "container-xxl"

editor: visual

